[package]
name = "nioruntime_deps"
version = "0.0.3-beta1"
authors = ["37 Miners, LLC"]
description = "dependencies for nioruntime"
license = "Apache-2.0"
repository = "https://github.com/37miners/nioruntime"
keywords = [ "rustlet", "nioruntime", "concord" ]
exclude = ["**/*.nio"]
edition = "2018"

[target.'cfg(target_os = "macos")'.dependencies]
kqueue-sys = "1.0.2"
[target.'cfg(target_os = "windows")'.dependencies]
wepoll-sys = "3.0.1"
ws2_32-sys = "0.2.1"
winapi = "0.2.8"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
futures = "0.3.0"
lazy_static = "1.4.0"
libc = "^0.2.17"
nix = "0.22.0"
chrono = "0.4"
rand = "0.8.4"
ed25519-dalek = "1"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1"
bytes = "0.5"
base64 = "0.13.0"
backtrace = "0.3.63"
rustls = { version = "0.20.4", features = [ "dangerous_configuration" ] }
blake2 = { package = "blake2-rfc", version = "0.2" }
rustls-pemfile = "0.2.0"
webpki-roots = "0.22"
num_enum = "0.5.6"
errno = "0.2.7"
portpicker = "0.1.1"
native-tls = "0.2.6"
x509-signature = "0.5.0"
colored = "2.0.0"
arrayref = "0.3.6"
caret = "0.0.3"
signature = "1"
hex-literal = "0.3"
digest = "0.10.0"
generic-array = "0.14.3"
typenum = "1.12"
cipher = "0.3.0"
zeroize = "1"
subtle = "2"
rand_core = "0.6.2"
hmac = "0.12.0"
hkdf = "0.12.0"
hex = "0.3.1"
byte-tools = "0.3.1"
bitvec = "1"
serde_derive = "1"
